# Generated by Django 5.2.3 on 2025-06-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0002_alter_message_model_sender'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Model',
        ),
    ]
