# Generated by Django 5.2.3 on 2025-06-13 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0002_alter_message_model_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message_model',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message_model',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
