# Generated by Django 5.2.3 on 2025-06-16 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0003_message_model_is_reported_message_model_reported_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message_model',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
