# Generated by Django 5.2.3 on 2025-06-17 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0004_message_model_bookmarked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_model',
            name='reported_by',
        ),
        migrations.CreateModel(
            name='Reported_Message_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse'), ('other', 'Other')], max_length=5)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_messages.message_model')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message_id', 'reporter')},
            },
        ),
    ]
