# Generated by Django 5.2.3 on 2025-06-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0006_message_model_reported_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reported_message_model',
            old_name='message_id',
            new_name='message',
        ),
    ]
